account:
  avatar:
    width: 150
    height: 150
base:
  baseurl: http://localhost:8082/
  isenableaccess: false
  isenablecode: false
  logpath: /data/log
  port: 8082
  sitename: Zeus 宙斯权限后台管理系统
  apiurl: http://localhost:8082
casbin:
  model:
    rule_0: config/casbin/rbac_model_0.conf
cors:
  allow_credentials: false
  allow_headers:
  - '*'
  allow_methods:
  - GET
  - POST
  - OPTIONS
  - PUT
  - DELETE
  allow_origins:
  - '*'
  enable: false
  max_age: 7200
database:
  driver: mysql
  mysql:
    charset: utf8
    host: 127.0.0.1:3306
    name: zeus
    password: Snow09lj
    pool:
      max: 20
      min: 5
    ssl: false
    user: root
  sqlite:
    dsn: data/zeus.db
dingtalk:
  agentid: 310135985
  appkey: dingvgvn9hdcp8qtarno
  appsecret: Sn887TtSQgGQNRcSaP-cNQXKYOkuT062vPgHoVvbTm5-HA2qnyew6xbdgZwhxD8N
  cachepath: data/
#  corpid: dingd60a58f4e3be699235c2f4657eb6378f
#  snsappid: dingoa1uudyxl2dcjvqpij
#  snssecret: o8YvDT5l2zb9dikuCbz0HXOiOaVwdyVResrDVyFaqojv0EwZp8ygAemFyoSBh_lz
#  ssosecret: XU3oARxOHw731w4LYEJodPEPtppX5oMa7XPp5dv2VjTLak9I--glTDBLLbcl2VpQ
domain: bullteam.local
email:
  smtp:
    address: ss@163.com
    password: xxxxxx
    port: 25
    server: smtp.163.com
    user: vcoso@163.com
jwt:
  expiresat: 3600*24*1
  key:
    private: keys/jwt_private_key.pem
    public: keys/jwt_public_key.pem
lang:
  names: 简体中文|English
  types: zh-CN|en-US
ldap:
  addr: 127.0.0.1:389
  attributes:
  - cn
  - displayName
  - mail
  authfilter: (&(uid=%s))
  basedn: dc=bullteam,dc=com
  binddn: cn=admin,dc=bullteam,dc=com
  bindpass: zeus@admin#123456
  starttls: false
  tls: false
  userdn: cn=admin,dc=bullteam,dc=com
mode: debug
project:
  merge: false
redis:
  host: 127.0.0.1:6379
  pool:
    max: 20
    min: 3
security:
  install_lock: false
